# Generated by Django 4.1.7 on 2023-04-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dispatcher_remove_consignee_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignee',
            options={'verbose_name': 'Consignee', 'verbose_name_plural': 'Consignees'},
        ),
        migrations.AlterModelOptions(
            name='consigneeaddress',
            options={'verbose_name': 'Consignee address', 'verbose_name_plural': 'Consignee addresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'Customer address', 'verbose_name_plural': 'Customer addresses'},
        ),
        migrations.AlterModelOptions(
            name='dispatcher',
            options={'verbose_name': 'Dispatcher', 'verbose_name_plural': 'Dispatchers'},
        ),
        migrations.AlterModelOptions(
            name='dispatcheraddress',
            options={'verbose_name': 'Dispatcher address', 'verbose_name_plural': 'Dispatcher addresses'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='driveraddress',
            options={'verbose_name': 'Driver address', 'verbose_name_plural': 'Driver addresses'},
        ),
        migrations.AlterModelOptions(
            name='shipper',
            options={'verbose_name': 'Shipper', 'verbose_name_plural': 'Shippers'},
        ),
        migrations.AlterModelOptions(
            name='shipperaddress',
            options={'verbose_name': 'Shipper address', 'verbose_name_plural': 'Shipper addresses'},
        ),
    ]
