# Generated by Django 4.1.7 on 2023-04-12 10:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Supplier's name")),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name="Company's name")),
                ('wechat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wechat id')),
                ('bzness_card', models.ImageField(blank=True, null=True, upload_to='media/business_cards/', verbose_name='Business Card')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone number')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.supplier')),
            ],
            options={
                'verbose_name': 'Supplier address',
                'verbose_name_plural': 'Supplier addresses',
            },
        ),
    ]
