# Generated by Django 4.1.7 on 2023-04-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature', models.DateField()),
                ('arrived', models.DateField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cbms', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ctns', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LooseContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allin.basecontainer')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('allin.basecontainer',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('types', models.CharField(blank=True, choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT')], default='', max_length=150, null=True)),
                ('qty', models.IntegerField()),
                ('packaging', models.IntegerField()),
                ('cbm', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock', models.IntegerField()),
                ('has_stock', models.BooleanField()),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='users.supplier')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_bought', to='users.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LooseCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=150, null=True)),
                ('recieved', models.DateField()),
                ('depature', models.DateField()),
                ('arrived', models.DateField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cbms', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ctns', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dispater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargos_dispatched', to='users.dispatcher')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargo', to='allin.product')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargos_dispatched', to='users.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='allin.loosecontainer')),
            ],
        ),
    ]
