# Generated by Django 4.2.3 on 2023-07-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('depature', models.DateField(blank=True, null=True, verbose_name='Loaded')),
                ('arrived', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True)),
                ('cbms', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ctns', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RW', 'China Warehouse'), ('DC', 'Shipped '), ('AT', 'In Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved')], default='RW', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('WH', 'In Warehouse'), ('VH', 'Delivering'), ('RC', 'Received')], default='WH', max_length=2)),
                ('delivery_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('plate_number', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('mileage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('last_checkup', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_reccuring', models.BooleanField()),
                ('recurrance', models.CharField(choices=[('N', 'Not Recurring'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quaterly'), ('S', 'Semi Annual'), ('A', 'Annual')], default='N', max_length=4)),
                ('notes', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FullCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=150, null=True)),
                ('recieved', models.DateField(blank=True, null=True)),
                ('depature', models.DateField(blank=True, null=True)),
                ('arrived', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cbms', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ctns', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RW', 'China Warehouse'), ('DC', 'Shipped '), ('AT', 'In Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved')], default='RW', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice number ')),
            ],
        ),
        migrations.CreateModel(
            name='LooseCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=150, null=True)),
                ('recieved', models.DateField(blank=True, null=True)),
                ('depature', models.DateField(blank=True, null=True)),
                ('arrived', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cbms', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ctns', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RW', 'China Warehouse'), ('DC', 'Shipped '), ('AT', 'In Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved')], default='RW', max_length=3)),
                ('invoice_number', models.CharField(blank=True, max_length=8, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='product name')),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('R', 'Reviewing'), ('Q', 'Quoted')], default='S', max_length=2)),
                ('contact', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('cbms', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ctns', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allin.basecontainer')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('allin.basecontainer',),
        ),
        migrations.CreateModel(
            name='LooseContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allin.basecontainer')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('allin.basecontainer',),
        ),
        migrations.CreateModel(
            name='ProductShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cbm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='allin.shippingquote')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuoteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frontend/src/media/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allin.productquote')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved', models.DateField(auto_now_add=True, null=True, verbose_name='(Warehouse)recieved on')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('chinese', models.CharField(blank=True, max_length=150, null=True, verbose_name='chinese desc')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='qty (ctn)')),
                ('packaging', models.IntegerField(blank=True, null=True, verbose_name='units/ctn')),
                ('units', models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('RLS', 'Rolls'), ('DZN', 'Dozens'), ('BGS', 'Bags'), ('SET', 'Set')], default='PCS', max_length=4, null=True)),
                ('prod_type', models.CharField(choices=[('HW', 'Hardware - 1'), ('HW', 'Hardware (wire mash, heavy hardware items)'), ('EL', 'Electronics'), ('TY', 'Toys'), ('CO', 'Cosmetics'), ('CL', 'Clothes'), ('ST', 'Stationery'), ('PA', 'Phone Accessories'), ('CC', 'Carpets and Curtains'), ('DC', 'Decor'), ('MS', 'Motorcycle spare parts'), ('OT', ''), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other'), ('OT', 'Other')], default='OT', max_length=4, verbose_name='Product Category')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Unit Price')),
                ('ttprice', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='T.T.Price')),
                ('cbm', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='CBM/ctns')),
                ('cbms', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Total CBM')),
                ('wght', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='weight/ctn')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='total weight')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('item_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cbm_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('cargo_types', models.CharField(blank=True, choices=[('F', 'Full Cont. Cargo'), ('L', 'Loose Cont. Cargo')], default='L', max_length=150, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('has_stock', models.BooleanField(default=False)),
                ('f_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='allin.fullcargo')),
                ('l_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='allin.loosecargo')),
            ],
        ),
    ]
