# Generated by Django 4.1.7 on 2023-04-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('allin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loosecargo',
            name='dispater',
        ),
        migrations.RemoveField(
            model_name='loosecargo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='types',
        ),
        migrations.AddField(
            model_name='basecontainer',
            name='status',
            field=models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('RC', 'Recieved by Client')], default='RW', max_length=3),
        ),
        migrations.AddField(
            model_name='loosecargo',
            name='dispature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargos_dispatched', to='users.dispatcher'),
        ),
        migrations.AddField(
            model_name='loosecargo',
            name='status',
            field=models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('RC', 'Recieved by Client')], default='RW', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='cargo_types',
            field=models.CharField(blank=True, choices=[('F', 'Full Cargo'), ('L', 'Loose Cargo')], default='L', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='l_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='allin.loosecargo'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='arrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='ctns',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='depature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='arrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='ctns',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='depature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='recieved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargos_dispatched', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_bought', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='FullContainer',
            fields=[
                ('basecontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='allin.basecontainer')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            bases=('allin.basecontainer',),
        ),
        migrations.CreateModel(
            name='FullCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=150, null=True)),
                ('recieved', models.DateField(blank=True, null=True)),
                ('depature', models.DateField(blank=True, null=True)),
                ('arrived', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cbms', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ctns', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('RC', 'Recieved by Client')], default='RW', max_length=3)),
                ('dispature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_cargos_dispatched', to='users.dispatcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of the expense')),
                ('is_reccuring', models.BooleanField()),
                ('recurrance', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quaterly'), ('S', 'Semi Annual'), ('A', 'Annual')], default='N', max_length=4)),
                ('notes', models.TextField()),
                ('dispature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.dispatcher')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='f_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='allin.fullcargo'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='users.supplier'),
        ),
    ]
