# Generated by Django 4.1.7 on 2023-04-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0002_remove_loosecargo_dispater_remove_loosecargo_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='allin.fullcontainer'),
        ),
        migrations.AddField(
            model_name='loosecargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='allin.loosecontainer'),
        ),
    ]
