# Generated by Django 4.2.3 on 2023-07-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('HW1', 'Hardware - 1'), ('HW2', 'HARDWARE (wire mash, heavy hardware items)'), ('MAB', 'MABATI'), ('COS', 'COSMETICS/PERFUME/TOOTHPASTE'), ('CL', 'CLOTHES'), ('ST', 'STATIONARY'), ('GE', 'GYM EQUIPMENTS'), ('MC', 'MACHINES'), ('CA', 'CAR SPARE PARTS'), ('MS', 'MOTORCYCLE SPARE PARTS'), ('TO', 'TOYS'), ('SH', 'SHOES'), ('CU', 'CURTAINS'), ('CF', 'CARPETS/ FLOOR MAT'), ('OR', 'ORNAMENTS'), ('DC', 'DECORATIONS'), ('SU', 'SUNGLASSES'), ('PA', 'PHONE ACCESSORIES'), ('TV', 'TV’S'), ('EL', 'ELECTRONICS'), ('FU', 'FURNITURE'), ('HO', 'HOSPITAL EQUIPMENTS I.E WHEEL CHAIRS'), ('OT', 'Other')], default='OT', max_length=4, verbose_name='Product Category'),
        ),
    ]
