# Generated by Django 4.1.7 on 2023-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0003_fullcargo_container_loosecargo_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='qty in ctn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
