# Generated by Django 4.1.7 on 2023-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0004_alter_product_has_stock_alter_product_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
