# Generated by Django 4.2.3 on 2023-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0005_alter_loosecargo_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price/CBM')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[], default='OT', max_length=4, verbose_name='Product Category'),
        ),
    ]
