# Generated by Django 4.1.7 on 2023-04-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0005_product_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecontainer',
            name='number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
