# Generated by Django 4.2.3 on 2023-08-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0006_productcategory_alter_product_prod_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('TOYS', 'TOYS'), ('SUNGLASSES', 'SUNGLASSES'), ('COSMETICS/PERFUME/TOOTHPASTE', 'COSMETICS/PERFUME/TOOTHPASTE'), ('STATIONARY', 'STATIONARY'), ('GYM EQUIPMENTS', 'GYM EQUIPMENTS'), ('ORNAMENTS', 'ORNAMENTS'), ('DECORATIONS', 'DECORATIONS'), ('PHONE ACCESSORIES', 'PHONE ACCESSORIES'), ('Hardware - 1', 'Hardware - 1'), ('CLOTHES', 'CLOTHES'), ('FURNITURE', 'FURNITURE'), ('MOTORCYCLE SPAREPARTS', 'MOTORCYCLE SPARE PARTS'), ('SHOES', 'SHOES'), ('CURTAINS', 'CURTAINS'), ('CARPETS/ FLOOR MAT', 'CARPETS/ FLOOR MAT'), ('TV', 'TV’S'), ('ELECTRONICS', 'ELECTRONICS'), ('HARDWARE (wire mash, heavy hardware items)', 'HARDWARE (wire mash, heavy hardware items)'), ('MABATI', 'MABATI'), ('MACHINES', 'MACHINES'), ('CAR SPAREPARTS', 'CAR SPARE PARTS'), ('HOSPITAL', 'HOSPITAL EQUIPMENTS I.E WHEEL CHAIRS'), ('Other', 'Other')], default='Other', max_length=150, verbose_name='Product Category'),
        ),
    ]
