# Generated by Django 4.1.7 on 2023-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0006_basecontainer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='recurrance',
            field=models.CharField(choices=[('N', 'Not Recurring'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quaterly'), ('S', 'Semi Annual'), ('A', 'Annual')], default='N', max_length=4),
        ),
    ]
