# Generated by Django 4.1.7 on 2023-04-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0007_expenses_amount_alter_expenses_recurrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
