# Generated by Django 4.1.7 on 2023-04-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0008_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Invoice number '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cargo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='allin.loosecargo'),
        ),
    ]
