# Generated by Django 4.2.3 on 2023-09-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0009_alter_loosecargo_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_per_cbm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='units/ctn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='qty (ctn)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
