# Generated by Django 4.1.7 on 2023-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0009_invoice_invoice_no_alter_invoice_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total CBM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CBM per cartons'),
        ),
    ]
