# Generated by Django 4.1.7 on 2023-05-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('allin', '0011_expense_expensecategory_delete_expenses_expense_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('plate_number', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('mileage', models.DecimalField(decimal_places=3, max_digits=6)),
                ('last_checkup', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('cbms', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProductShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cbm', models.DecimalField(decimal_places=3, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allin.shippingquote')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuoteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='frontend/src/media/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allin.productquote')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driver')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allin.deliveryvehicle')),
            ],
        ),
        migrations.AddField(
            model_name='loosecargo',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='allin.delivery'),
        ),
    ]
