# Generated by Django 4.1.7 on 2023-05-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0012_deliveryvehicle_productquote_shippingquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquote',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productquote',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productquote',
            name='name',
            field=models.CharField(max_length=150, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='productshippingquote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allin.shippingquote'),
        ),
    ]
