# Generated by Django 4.1.7 on 2023-05-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0013_productquote_contact_productquote_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshippingquote',
            name='total_cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productshippingquote',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingquote',
            name='ctns',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productshippingquote',
            name='product',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='allin.shippingquote'),
            preserve_default=False,
        ),
    ]
