# Generated by Django 4.1.7 on 2023-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0014_productshippingquote_total_cbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshippingquote',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='ctns',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shippingquote',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
