# Generated by Django 4.1.7 on 2023-05-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0015_alter_productshippingquote_total_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('WH', 'In TZ Warehouse'), ('VH', 'Loaded in Vehicle'), ('RC', 'Received by Customer')], default='WH', max_length=2),
        ),
    ]
