# Generated by Django 4.1.7 on 2023-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0016_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquote',
            name='status',
            field=models.CharField(choices=[('S', 'Submitted'), ('R', 'Reviewing'), ('Q', 'Quoted')], default='S', max_length=2),
        ),
    ]
