# Generated by Django 4.2.2 on 2023-06-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0017_alter_productquote_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
    ]
