# Generated by Django 4.2.2 on 2023-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0019_alter_deliveryvehicle_options_product_chinese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontainer',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='ctns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='ctns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='cbms',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='ctns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='qty (ctn)'),
        ),
    ]
