# Generated by Django 4.2.2 on 2023-06-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('allin', '0020_alter_basecontainer_cbms_alter_basecontainer_ctns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcontainer',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
