# Generated by Django 4.2.2 on 2023-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0021_alter_fullcontainer_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('RLS', 'Rolls'), ('DZN', 'Dozens'), ('BGS', 'Bags'), ('SET', 'Set')], default='PCS', max_length=4, null=True),
        ),
    ]
