# Generated by Django 4.2.2 on 2023-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0022_alter_product_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recieved',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='(Warehouse)recieved on'),
        ),
        migrations.AlterField(
            model_name='basecontainer',
            name='depature',
            field=models.DateField(blank=True, null=True, verbose_name='Loaded'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
