# Generated by Django 4.2.2 on 2023-07-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0023_product_recieved_alter_basecontainer_depature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loosecargo',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
