# Generated by Django 4.2.2 on 2023-07-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('allin', '0024_loosecargo_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.driver'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allin.deliveryvehicle'),
        ),
    ]
