# Generated by Django 4.2.2 on 2023-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0025_alter_delivery_driver_alter_delivery_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
