# Generated by Django 4.2.2 on 2023-07-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('allin', '0026_delivery_delivery_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allin.deliveryvehicle'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dispature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='users.dispatcher'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allin.expensecategory', verbose_name='Name of the expense'),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='allin.fullcontainer'),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='dispature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_cargos_dispatched', to='users.dispatcher'),
        ),
        migrations.AlterField(
            model_name='fullcontainer',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cargo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='allin.loosecargo'),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='allin.loosecontainer'),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='allin.delivery'),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='dispature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_cargos_dispatched', to='users.dispatcher'),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loose_cargos_dispatched', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_bought', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='f_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='allin.fullcargo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='l_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='allin.loosecargo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='users.supplier'),
        ),
        migrations.AlterField(
            model_name='productquoteimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allin.productquote'),
        ),
    ]
