# Generated by Django 4.2.2 on 2023-07-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0027_alter_delivery_driver_alter_delivery_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
