# Generated by Django 4.2.2 on 2023-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allin', '0029_alter_delivery_driver_alter_expense_dispature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontainer',
            name='status',
            field=models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved by Customer')], default='RW', max_length=3),
        ),
        migrations.AlterField(
            model_name='fullcargo',
            name='status',
            field=models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved by Customer')], default='RW', max_length=3),
        ),
        migrations.AlterField(
            model_name='loosecargo',
            name='status',
            field=models.CharField(choices=[('RW', 'Recieved in China Warehouse'), ('DC', 'Departed China '), ('AT', 'Arrived in Tanzania'), ('DV', ' Delivering'), ('RC', 'Recieved by Customer')], default='RW', max_length=3),
        ),
    ]
