# Generated by Django 4.1.7 on 2023-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_product_transfer_invoice_expenses_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('RMB', 'RMB')], default='RMB', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('RMB', 'RMB')], default='RMB', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT')], default='PRODUCT', max_length=7, null=True, verbose_name='Product or Service'),
        ),
    ]
