# Generated by Django 4.1.7 on 2023-04-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('shipping', '0003_loosecontainer_loosecargoinvoice_loosecargo_and_more'),
        ('finance', '0003_alter_invoice_currency_alter_product_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Packaging',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='No. of items in a carton'),
        ),
        migrations.AddField(
            model_name='product',
            name='chinese_det',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chinese details'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shipping.fullcargo'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Height in centimeters'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Product/Item's number"),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Length  in centimeters'),
        ),
        migrations.AddField(
            model_name='product',
            name='loose_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shipping.loosecargo'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('ROLLS', 'Rolls'), ('DOZENS', 'Dozens'), ('BAGS', 'Bags')], default='PCS', max_length=15, null=True, verbose_name=' Unit packaging type'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_pic'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='CBM per carton'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Weight per carton in KG'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Width  in centimeters'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Unit price(price/pcs)'),
        ),
    ]
