# Generated by Django 4.1.7 on 2023-04-19 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_product_packaging_product_chinese_det_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_cargo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='loose_cargo',
        ),
    ]
