# Generated by Django 4.1.7 on 2023-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_product_full_cargo_remove_product_loose_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='product( unregistered/ random)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Packaging',
            new_name='packaging',
        ),
    ]
