# Generated by Django 4.1.7 on 2023-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_otherproduct_rename_packaging_product_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'SERVICE'), ('P', 'PRODUCT')], default='PRODUCT', max_length=7, null=True, verbose_name='Product or Service'),
        ),
    ]
