# Generated by Django 4.2.2 on 2023-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('RLS', 'Rolls'), ('DZN', 'Dozens'), ('BGS', 'Bags')], default='PCS', max_length=15, null=True, verbose_name=' Unit packaging type'),
        ),
    ]
