# Generated by Django 4.2.2 on 2023-07-05 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0009_remove_fullcargoinvoice_cargo_and_more'),
        ('finance', '0009_alter_product_packaging_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.DeleteModel(
            name='OtherProduct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='from_ac',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_ac',
        ),
        migrations.AlterField(
            model_name='account',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
