export const CARGO_LIST_REQUEST = 'CARGO_LIST_REQUEST'
export const CARGO_LIST_SUCCESS = 'CARGO_LIST_SUCCESS'
export const CARGO_LIST_FAIL = 'CARGO_LIST_FAIL'

export const CARGO_DETAILS_REQUEST = 'CARGO_DETAILS_REQUEST'
export const CARGO_DETAILS_SUCCESS = 'CARGO_DETAILS_SUCCESS'
export const CARGO_DETAILS_FAIL = 'CARGO_DETAILS_FAIL'
