export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST'
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS'
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL'

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST'
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS'
export const INVOICE_DETAILS_FAIL = 'INVOICE_DETAILS_FAIL'
