# Generated by Django 4.1.7 on 2023-04-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_dispatcher_remove_consignee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_expiry_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('DOT_inspection_date', models.DateField(blank=True, null=True)),
                ('quaterly_inspection_date', models.DateField(blank=True, null=True, verbose_name='90 days inspection date')),
                ('annual_inspection_date', models.DateField(blank=True, null=True)),
                ('truck', models.CharField(blank=True, max_length=100, null=True)),
                ('trailer', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('axels', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('IFTA_truck', models.BooleanField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='users.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_number', models.CharField(blank=True, max_length=10, null=True)),
                ('load_name', models.CharField(blank=True, max_length=100, null=True)),
                ('load_type', models.CharField(blank=True, max_length=3, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Pick up date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('line_haul_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('unloading_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('detention_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('layovers_fee', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('other_charges', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('total_rates', models.DecimalField(blank=True, decimal_places=3, max_digits=4, max_length=6, null=True)),
                ('empty_M', models.CharField(blank=True, max_length=100, null=True)),
                ('loaded_M', models.CharField(blank=True, max_length=100, null=True)),
                ('per_mile', models.CharField(blank=True, max_length=100, null=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.consignee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.driver')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='users.shipper')),
            ],
        ),
    ]
