# Generated by Django 4.1.7 on 2023-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_supplier_supplieraddress'),
        ('shipping', '0002_alter_shipment_load_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LooseContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall weight')),
                ('ctns', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Number of cartons')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall amount')),
                ('container_number', models.CharField(blank=True, max_length=30, null=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_container_dispatched', to='users.dispatcher')),
            ],
        ),
        migrations.CreateModel(
            name='LooseCargoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cargo', models.ManyToManyField(blank=True, related_name='invoices', to='shipping.loosecontainer')),
            ],
        ),
        migrations.CreateModel(
            name='LooseCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity in cartons')),
                ('total_pcs', models.IntegerField(blank=True, null=True, verbose_name='Total Pieces')),
                ('total_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='weight in KG')),
                ('container_number', models.CharField(blank=True, max_length=30, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargo_checked', to='users.dispatcher')),
                ('loose_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='shipping.loosecontainer')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loose_cargos', to='users.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall weight')),
                ('ctns', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Number of cartons')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall amount')),
                ('container_number', models.CharField(blank=True, max_length=30, null=True)),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_container_dispatched', to='users.dispatcher')),
            ],
        ),
        migrations.CreateModel(
            name='FullCargoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('cargo', models.ManyToManyField(blank=True, related_name='invoice', to='shipping.fullcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='FullCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Quantity in cartons')),
                ('total_pcs', models.IntegerField(blank=True, null=True, verbose_name='Total Pieces')),
                ('total_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='weight in KG')),
                ('container_number', models.CharField(blank=True, max_length=30, null=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_cargo_checked', to='users.dispatcher')),
                ('full_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='shipping.fullcontainer')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_cargos', to='users.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
