# Generated by Django 4.1.7 on 2023-04-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_loosecontainer_loosecargoinvoice_loosecargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcontainer',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall weight'),
        ),
        migrations.AddField(
            model_name='fullcontainer',
            name='depature',
            field=models.DateField(blank=True, null=True, verbose_name='Depature date'),
        ),
        migrations.AddField(
            model_name='fullcontainer',
            name='status',
            field=models.CharField(blank=True, choices=[('NF', 'Not Full'), ('FC', 'Full CBM'), ('OW', 'Over weight'), ('NC', 'Needs Confirming')], default='NF', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='loosecontainer',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall weight'),
        ),
        migrations.AddField(
            model_name='loosecontainer',
            name='depature',
            field=models.DateField(blank=True, null=True, verbose_name='Depature date'),
        ),
        migrations.AddField(
            model_name='loosecontainer',
            name='status',
            field=models.CharField(blank=True, choices=[('NF', 'Not Full'), ('FC', 'Full CBM'), ('OW', 'Over weight'), ('NC', 'Needs Confirming')], default='NF', max_length=5, null=True),
        ),
    ]
