# Generated by Django 4.1.7 on 2023-04-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_product_full_cargo_remove_product_loose_cargo'),
        ('shipping', '0004_fullcontainer_cbm_fullcontainer_depature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcargo',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='full_cargos', to='finance.product', verbose_name='cargo/product'),
        ),
        migrations.AddField(
            model_name='loosecargo',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='loose_cargos', to='finance.product', verbose_name='cargo/product'),
        ),
        migrations.AlterField(
            model_name='fullcontainer',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall CBM'),
        ),
        migrations.AlterField(
            model_name='loosecontainer',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Overall CBM'),
        ),
    ]
