# Generated by Django 4.1.7 on 2023-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_fullcargo_product_loosecargo_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loosecontainer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Holder Name'),
        ),
    ]
