# Generated by Django 4.1.7 on 2023-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_loosecontainer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullcontainer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Holder Name'),
        ),
    ]
